### PR TITLE
Remove unused css from json

### PR DESCRIPTION
**Pull request by cef62**
Now the module remove non existent classes from the final output

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Wow, it works like a charm.

I just wonder if we should move the `clearJsonMap` function into a separate "module", I'm worried that the `compiler` module is getting too big.
What do you think?

I also restarted the builds, I'm not sure why they are still "pending".

**Comment by cef62** [comment]
I agree with you, I think the `compiler` module should be divided in several smaller files and refactored to be a `compiler` folder module. I'll push some more commits in few minutes and then after we merge we should move the `compiler` revision on another PR.

**Comment by cef62** [comment]
I know the tests are not directly related with the new features but was easier to start to integrate them here.

**Comment by MicheleBertoli** [comment]
Perfect, let's merge this!

**Comment by MicheleBertoli** [comment]
main-qimg-c8781a4bb1f17e330b50cb35f851da05-c

**Pull request merged**
